apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  clusterIP: None
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
  selector:
    app: memcached